const sampleReceiptText = 'WHOLE\nFOODS\nAmerica\'s Healthlest Grocery Store"\nUFM CLEMENTINE BAG\nSYDLC CNUT COFE CR\nCROFT STRAUBRY SPR\n6.99 F\n3.49 F\n4.99 F\n1,19 LB 2.49 b\nUT\nTARE01\nBEANS GREEN\n2.96 F\nITEM 4066\nVIRGL CREAM SODA\nIMA TOMATO BASIL S\nBULK ALMOND BUTTER\nHTICA PARM REG GRA\nBC NF VAN GRK YGRT\nBC NF VANGRK YGRT\n365 LT CHNK TUNA\nBC NF VAN GRK YGRT\nBC NF VAN GRK YGRT\nANCH 0G CINN HOT D\nBLACKBERRIES\nBRM THCK RLD DATS\n4.99 B\n3,99 F\n5.77 F\n4.23 F\n1.39F\n1.39 F\n2.59 F\n1 39 F\n1,39 F\n6.99 F\n3.99 F\n4.99 F\nARE01\n2.33 LB 99 Ib\nBANANA 06\nUT\n2.31 F\nITEM 94237\nMP\nBAG REFUND\n10\nITEM 486408\n46-F\n35\nCPITEM 20% OFF Bananas!\nTax 7.00%\nTAX\n35 BAL 63.63\n'

const sampleReceiptAmt =
[ { data: 6.99,
    text: 'UFM CLEMENTINE BAG 6.99 F',
    regions: [Array],
    index: 4,
    _rows: [Array],
    description: 'UFM CLEMENTINE BAG 6.99' },
  { data: 3.49,
    text: 'SYDLC CNUT COFE CR 3.49 F',
    regions: [Array],
    index: 5,
    _rows: [Array],
    description: 'SYDLC CNUT COFE CR 3.49' },
  { data: 4.99,
    text: 'CROFT STRAUBRY SPR 4.99 F',
    regions: [Array],
    index: 6,
    _rows: [Array],
    description: 'CROFT STRAUBRY SPR 4.99 1,19 LB 2.49 b TARE01' },
  { data: 2.49,
    text: '1,19 LB 2.49 b TARE01',
    regions: [Array],
    index: 7 },
  { data: 2.96,
    text: 'UT BEANS GREEN 2.96 F',
    regions: [Array],
    index: 8,
    _rows: [Array],
    description: 'UT BEANS GREEN 2.96 ITEM 4066' },
  { data: 4.99,
    text: 'VIRGL CREAM SODA 4.99 B',
    regions: [Array],
    index: 10,
    _rows: [Array],
    description: 'VIRGL CREAM SODA 4.99' },
  { data: 3.99,
    text: 'IMA TOMATO BASIL S 3,99 F',
    regions: [Array],
    index: 11,
    _rows: [Array],
    description: 'IMA TOMATO BASIL S 3,99' },
  { data: 5.77,
    text: 'BULK ALMOND BUTTER 5.77 F',
    regions: [Array],
    index: 12,
    _rows: [Array],
    description: 'BULK ALMOND BUTTER 5.77' },
  { data: 4.23,
    text: 'HTICA PARM REG GRA 4.23 F',
    regions: [Array],
    index: 13,
    _rows: [Array],
    description: 'HTICA PARM REG GRA 4.23' },
  { data: 1.39,
    text: 'BC NF VAN GRK YGRT 1.39 F',
    regions: [Array],
    index: 14,
    _rows: [Array],
    description: 'BC NF VAN GRK YGRT 1.39' },
  { data: 1.39,
    text: 'BC NF VAN GRK YGRT 1.39 F',
    regions: [Array],
    index: 15,
    _rows: [Array],
    description: 'BC NF VAN GRK YGRT 1.39' },
  { data: 2.59,
    text: '365 LT CHNK TUNA 2.59 F',
    regions: [Array],
    index: 16,
    _rows: [Array],
    description: '365 LT CHNK TUNA 2.59 BC NF VAN GRK YGRT 1 39 F' },
  { data: 1.39,
    text: 'BC NF VAN GRK YGRT 1,39 F',
    regions: [Array],
    index: 18,
    _rows: [Array],
    description: 'BC NF VAN GRK YGRT 1,39' },
  { data: 6.99,
    text: 'ANCH 0G CINN HOT D 6.99 F',
    regions: [Array],
    index: 19,
    _rows: [Array],
    description: 'ANCH 0G CINN HOT D 6.99' },
  { data: 3.99,
    text: 'BLACKBERRIES 3.99 F',
    regions: [Array],
    index: 20,
    _rows: [Array],
    description: 'BLACKBERRIES 3.99' },
  { data: 4.99,
    text: 'BRM THCK RLD DATS 4.99 F',
    regions: [Array],
    index: 21,
    _rows: [Array],
    description: 'BRM THCK RLD DATS 4.99' },
  { data: 2.33,
    text: '2.33 LB 99 Ib ARE01',
    regions: [Array],
    index: 22,
    _rows: [Array],
    description: '2.33 LB 99 Ib' },
  { data: 2.31,
    text: 'UT BANANA 06 2.31 F',
    regions: [Array],
    index: 23,
    _rows: [Array],
    description: 'UT BANANA 06 2.31 ITEM 94237' },
  { data: 7,
    text: 'Tax 7.00 %',
    regions: [Array],
    index: 29,
    classifyResult: 'primaryTax',
    confidenceLevel: 0.17857142857142858 },
  { data: 63.63,
    text: '35 BAL 63.63',
    regions: [Array],
    index: 30,
    _rows: [Array],
    description: '35 BAL' } ];

    module.exports = {sampleReceiptAmt, sampleReceiptText}

